language: objective-c
osx_image: xcode8

install:
  - export ARCHS="x86_64"   # Only build dependencies for x86_64 to speed things up
  - bash ./scripts/build-all.sh
  - bundle install
  - bundle exec pod install

script:
  - set -o pipefail
  - xcodebuild -workspace OTRKit.xcworkspace -scheme OTRKitTestsiOS -sdk iphonesimulator -destination 'name=iPhone 6' test | xcpretty -c
  