language: objective-c
osx_image: xcode7.1

install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet # Need Cocoapods >= 0.34.1
  - export ARCHS="i386"   # Only build dependencies for i386 to speed things up
  - bash ./scripts/build-all.sh
  - pod install

script:
  - xctool -workspace OTRKit.xcworkspace -scheme OTRKitTestsiOS -sdk iphonesimulator -arch i386 test
